"""
=============================================================================
Soil Nutrient Prediction Inference Script (N, P, K)
=============================================================================
This script loads the three pre-trained Random Forest models and the stored
feature column order from the 'models/' directory to predict Nitrogen (N),
Phosphorus (P), and Potassium (K) for new remote-sensing input observations.

Educational Walkthrough:
------------------------
1. joblib.load() restores the trained Random Forest estimators and feature list.
2. The input observation is formatted as a pandas DataFrame matching the exact
   feature names and sequence used during training.
3. Each model outputs a continuous regression estimate for its respective nutrient.
4. Note: This is an AI/ML prototype trained on a synthetic dataset for pipeline
   demonstration and does not provide fertilizer dosage recommendations.
=============================================================================
"""

import os
import joblib
import pandas as pd

def load_models_and_features(models_dir="models"):
    """
    Loads the trained Random Forest models and feature name list using joblib.
    """
    nitrogen_model_path = os.path.join(models_dir, "nitrogen_model.pkl")
    phosphorus_model_path = os.path.join(models_dir, "phosphorus_model.pkl")
    potassium_model_path = os.path.join(models_dir, "potassium_model.pkl")
    features_path = os.path.join(models_dir, "feature_names.pkl")

    # Check that model files exist
    for p in [nitrogen_model_path, phosphorus_model_path, potassium_model_path, features_path]:
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"Required model artifact '{p}' not found! "
                "Please run 'python train_npk_models.py' first to train and save the models."
            )

    print(f"Loading trained models from '{models_dir}/'...")
    model_N = joblib.load(nitrogen_model_path)
    model_P = joblib.load(phosphorus_model_path)
    model_K = joblib.load(potassium_model_path)
    feature_names = joblib.load(features_path)

    return model_N, model_P, model_K, feature_names


def predict_soil_nutrients(input_data: dict, models_dir="models"):
    """
    Predicts Nitrogen, Phosphorus, and Potassium for a given dictionary of features.
    """
    # 1. Load models and exact feature column order
    model_N, model_P, model_K, feature_names = load_models_and_features(models_dir)

    # 2. Convert dictionary into a pandas DataFrame matching feature_names
    input_df = pd.DataFrame([input_data])[feature_names]

    # 3. Generate predictions using each specialized Random Forest model
    pred_N = model_N.predict(input_df)[0]
    pred_P = model_P.predict(input_df)[0]
    pred_K = model_K.predict(input_df)[0]

    return {
        "N": pred_N,
        "P": pred_P,
        "K": pred_K
    }


def main():
    print("=" * 65)
    print("      AGRICULTURAL AI: PREDICT SOIL NUTRIENTS (N, P, K)")
    print("=" * 65)

    # Sample input observation from user specification
    sample_input = {
        "NDVI": 0.72,
        "EVI": 0.48,
        "FVC": 0.76,
        "LAI": 3.4,
        "NDVI Texture": 0.06,
        "Biomass": 6.2
    }

    print("\n[Input Remote-Sensing Features]:")
    for feature_name, value in sample_input.items():
        print(f" - {feature_name:<15}: {value}")

    # Generate predictions
    predictions = predict_soil_nutrients(sample_input)

    print("\n" + "=" * 65)
    print("                    PREDICTED SOIL NUTRIENTS")
    print("=" * 65)
    print(f"Predicted Nitrogen   (N) : {predictions['N']:.2f} kg/ha")
    print(f"Predicted Phosphorus (P) : {predictions['P']:.2f} kg/ha")
    print(f"Predicted Potassium  (K) : {predictions['K']:.2f} kg/ha")
    print("=" * 65)
    print("\n[IMPORTANT NOTICE]:")
    print("These estimates are generated by the prototype Random Forest models")
    print("trained on the synthetic dataset. They demonstrate the ML inference")
    print("pipeline, but are NOT scientifically validated for real agricultural")
    print("use or field application. No fertilizer quantities are calculated yet.")
    print("=" * 65)


if __name__ == "__main__":
    main()
